# MFT Statistical Arbitrage Analyzer Configuration
input_data_directory: "../visualization/data/"
output_directory: "data/output/"
min_correlation_threshold: 0.7
max_cointegration_pvalue: 0.05
min_data_points: 100
require_same_sector: false
num_threads: 0
enable_simd: true
enable_caching: true
export_excel: true
export_csv: true
export_json: false
output_filename: "statistical_arbitrage_opportunities"
max_capital: 5000.0
max_positions: 5
min_stock_price: 10.0
max_stock_price: 500.0
max_position_risk: 0.20
min_expected_return: 0.05
